import html
from typing import Any, List

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from coreason_auditor.models import AuditPackage
from coreason_auditor.utils.logger import logger


class PDFReportGenerator:
    """
    Generates the CoReason Audit Package PDF report.
    """

    def generate_report(self, audit_package: AuditPackage, output_path: str) -> None:
        """
        Generates a PDF report from the AuditPackage.

        Args:
            audit_package: The data to report.
            output_path: The file path to save the PDF.
        """
        logger.info(f"Generating PDF report for Audit Package {audit_package.id} at {output_path}")

        doc = SimpleDocTemplate(output_path, pagesize=letter)
        styles = getSampleStyleSheet()
        story: List[Any] = []

        # Custom Styles
        title_style = styles["Title"]
        heading_style = styles["Heading2"]
        normal_style = styles["Normal"]

        # --- Header ---
        story.append(Paragraph("CoReason Audit Report", title_style))
        story.append(Spacer(1, 12))

        header_data = [
            ["Generated At:", audit_package.generated_at.strftime("%Y-%m-%d %H:%M:%S UTC")],
            ["Agent Version:", audit_package.agent_version],
            ["Package ID:", str(audit_package.id)],
            ["Generated By:", audit_package.generated_by],
        ]
        story.append(self._create_info_table(header_data))
        story.append(Spacer(1, 24))

        # --- AI-BOM Section ---
        story.append(Paragraph("1. AI-BOM Inventory", heading_style))
        story.append(Spacer(1, 6))

        bom = audit_package.bom
        bom_data = [
            ["Model Identity:", Paragraph(bom.model_identity, normal_style)],
        ]
        story.append(self._create_info_table(bom_data))
        story.append(Spacer(1, 12))

        # Data Lineage
        story.append(Paragraph("Data Lineage (Ingestion Jobs):", styles["Heading3"]))
        if bom.data_lineage:
            lineage_data = [[job] for job in bom.data_lineage]
            story.append(self._create_list_table(lineage_data, ["Job ID"]))
        else:
            story.append(Paragraph("No data lineage records found.", normal_style))
        story.append(Spacer(1, 12))

        # Dependencies
        story.append(Paragraph("Software Dependencies:", styles["Heading3"]))
        if bom.software_dependencies:
            # Chunk dependencies to save space if needed, or just list them
            # Let's list top 10 or all? All is safer for audit.
            dep_data = [[dep] for dep in bom.software_dependencies]
            story.append(self._create_list_table(dep_data, ["PackageSpec"]))
        else:
            story.append(Paragraph("No dependencies listed.", normal_style))
        story.append(Spacer(1, 24))

        # --- Traceability Matrix Section ---
        story.append(Paragraph("2. Requirement Traceability Matrix (RTM)", heading_style))
        story.append(Paragraph(f"Overall Status: {audit_package.rtm.overall_status.value}", normal_style))
        story.append(Spacer(1, 6))

        rtm_table_data = self._build_rtm_table_data(audit_package)
        story.append(self._create_data_table(rtm_table_data, col_widths=[60, 200, 80, 150]))
        story.append(Spacer(1, 24))

        # --- Deviation Report Section ---
        story.append(Paragraph("3. Deviation Report", heading_style))
        story.append(Spacer(1, 6))

        if audit_package.deviation_report:
            deviation_table_data = self._build_deviation_table_data(audit_package.deviation_report)
            story.append(self._create_data_table(deviation_table_data, col_widths=[100, 100, 60, 200]))
        else:
            story.append(Paragraph("No deviations reported.", normal_style))

        story.append(Spacer(1, 24))

        # --- Signature Placeholder ---
        # The actual signature is applied later, but we can show the hash if present
        if audit_package.document_hash:
            story.append(Paragraph("Document Security", heading_style))
            story.append(Paragraph(f"Document Hash (SHA-256): {audit_package.document_hash}", normal_style))

        doc.build(story)
        logger.info("PDF generation successful.")

    def _create_info_table(self, data: List[List[Any]]) -> Table:
        """Creates a simple 2-column info table."""
        t = Table(data, colWidths=[120, 350])
        t.setStyle(
            TableStyle(
                [
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        return t

    def _create_list_table(self, data: List[List[str]], headers: List[str]) -> Table:
        """Creates a simple list table with a header."""
        table_data = [headers] + data
        t = Table(table_data, colWidths=[400])
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ]
            )
        )
        return t

    def _create_data_table(self, data: List[List[Any]], col_widths: List[int]) -> Table:
        """Creates a detailed data table with headers."""
        t = Table(data, colWidths=col_widths, repeatRows=1)
        t.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("LEFTPADDING", (0, 0), (-1, -1), 4),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ]
            )
        )
        return t

    def _build_rtm_table_data(self, audit_package: AuditPackage) -> List[List[Any]]:
        """Constructs the RTM table data rows."""
        headers = ["Req ID", "Description", "Status", "Tests"]
        rows = [headers]

        styles = getSampleStyleSheet()
        normal_style = styles["Normal"]

        # Map tests for lookup
        test_map = {t.test_id: t for t in audit_package.rtm.tests}

        for req in audit_package.rtm.requirements:
            req_id = req.req_id
            # Sanitize description to prevent XML parsing errors in Paragraph
            safe_desc = html.escape(req.desc)
            desc = Paragraph(safe_desc, normal_style)  # Wrap text

            # Determine status for this specific requirement
            # The RTM object has overall_status, but we need per-requirement status logic
            # Re-using logic from TraceabilityEngine conceptually, or just listing tests

            linked_test_ids = audit_package.rtm.coverage_map.get(req_id, [])

            test_summaries = []
            req_status = "PASSED"

            if not linked_test_ids:
                req_status = "UNCOVERED"

            for tid in linked_test_ids:
                test = test_map.get(tid)
                if test:
                    test_summaries.append(f"{tid}: {test.result}")
                    if test.result != "PASS":
                        req_status = "FAILED"
                else:
                    test_summaries.append(f"{tid}: MISSING")
                    req_status = "FAILED"

            test_column_text = Paragraph(", ".join(test_summaries), normal_style)

            rows.append([req_id, desc, req_status, test_column_text])

        return rows

    def _build_deviation_table_data(self, deviations: List[Any]) -> List[List[Any]]:
        """Constructs the Deviation Report table data rows."""
        headers = ["Session ID", "Timestamp", "Risk", "Violation"]
        rows = [headers]

        styles = getSampleStyleSheet()
        normal_style = styles["Normal"]

        for dev in deviations:
            # Expect dict, handle missing keys gracefully
            sess_id = str(dev.get("session_id", "N/A"))
            ts = str(dev.get("timestamp", "N/A"))
            risk = str(dev.get("risk_level", "Unknown"))

            raw_summary = str(dev.get("violation_summary", "No details"))
            safe_summary = html.escape(raw_summary)
            violation = Paragraph(safe_summary, normal_style)

            rows.append([sess_id, ts, risk, violation])

        return rows
